# -*- coding: utf-8 -*-
"""Dominos_Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TcuofrQmT9ENnb_GkevRh2mHAk4ZdO57
"""

import os
os.chdir('/content/drive/MyDrive/Colab Notebooks/Scraper_Interview')
os.getcwd()

!pip install google-play-scraper

from google_play_scraper import Sort, reviews_all
import pandas as pd

#Because of the Google Play Store limit (up to 200 reviews can be fetched at a time), http requests are generated as long as the number of app reviews is divided by 200. 
#For example, targeting an app like Zomato makes tens of thousands of http requests.

result = reviews_all(
    'com.application.zomato',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    filter_score_with=None # defaults to None(means all score)
)
df = pd.DataFrame(result)[['userName','content','score']]
df.columns = ['User Name','Review','Rating']

df.set_index('User Name',drop = True)

df[(df['Rating'] == 5) | (df['Rating'] == 1)]

result1 = reviews_all(
    'com.application.zomato',
    sleep_milliseconds = 0, # defaults to 0
    lang = 'en', # defaults to 'en'
    country = 'us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    filter_score_with = 1 # defaults to None(means all score)
)

df1 = pd.DataFrame(result1)[['userName','content','score']]
df1.columns = ['User Name','Review','Rating']

#df1.set_index('User Name',drop = True)

result2 = reviews_all(
    'com.application.zomato',
    sleep_milliseconds = 0, # defaults to 0
    lang = 'en', # defaults to 'en'
    country = 'us', # defaults to 'us'
    sort = Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    filter_score_with = 2 # defaults to None(means all score)
    )

df2 = pd.DataFrame(result2)[['userName','content','score']]
df2.columns = ['User Name','Review','Rating']

#df2.set_index('User Name',drop = True)

result3 = reviews_all(
    'com.application.zomato',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    filter_score_with=3 # defaults to None(means all score)
)
df3 = pd.DataFrame(result3)[['userName','content','score']]
df3.columns = ['User Name','Review','Rating']

#df3.set_index('User Name',drop = True)

result4 = reviews_all(
    'com.application.zomato',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    filter_score_with=4 # defaults to None(means all score)
)
df4 = pd.DataFrame(result4)[['userName','content','score']]
df4.columns = ['User Name','Review','Rating']

#df4.set_index('User Name',drop = True)

result5 = reviews_all(
    'com.application.zomato',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    filter_score_with=5 # defaults to None(means all score)
)
df5 = pd.DataFrame(result5)[['userName','content','score']]
df5.columns = ['User Name','Review','Rating']

#df5.set_index('User Name',drop = True)

#len(result1 + result2 + result3 + result4 + result5)